### ISSUE TITLE
Failed to download PAC-script from addresses

### ISSUE THREAD

**Issue by anbrikzone** [anticensority/runet-censorship-bypass#106]
Всем добрый день.

К этой ошибке приводит следующая последовательность действий:
1. Щелкаю по иконке расширения в браузере
2. Выбираю Antizapret
3. Вываливается сообщение об ошибке
4. Сами сайты с PAC-скриптами открываются без всяких трудностей. Почему расширение не может их подтянуть - не понятно.

```
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.55",
  "pup-ext-err": {
    "message": "Failed to download PAC-script from addresses: [ https://antizapret.prostovpn.org/proxy.pac , https://rebrand.ly/ac-antizapret-pac ].",
    "wrapped": {
      "message": "Что-то не так с сетью, проверьте соединение.",
      "wrapped": {
        "stack": "TypeError: Failed to fetch\n    at Object.get (chrome-extension://npgcnondjocldhldegnakemclmfkngch/13-http-lib.js:45:7)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:222:44\n    at new Promise (<anonymous>)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:221:19",
        "message": "Failed to fetch",
        "name": "TypeError"
      }
    }
  }
}
```

**Comment by ilyaigpetrov** [comment]
Попробуйте переустановить расширение.
Также см.
https://rebrand.ly/ac-problems#user-content-Не-удалось-скачать-pac-скрипт-с-адресов--httpsantizapretprostovpnorgproxypac-
.

**Comment by anbrikzone** [comment]
Спасибо. Переустановка помогла.
