### ISSUE TITLE
Расширение перестало работать

### ISSUE THREAD

**Issue by ssbugman** [anticensority/runet-censorship-bypass#273]
Со вчерашнего дня сайты перестали грузиться, все другие расширения выключены.
Нажатие на "обновить" ничего не дает, процесс просто зависает на этапе "обновляем" и в консоли также пишет лишь это:
GET https://gateway.pinata.cloud/ipfs/QmYhCFAfMAp9sL3MQrSzThVvGG5uVkc654tsEobR58NRUW/proxy-ssl.js
Calling CB...
Дальше ничего, на этом обновление видимо зависает.
upd:
Через несколько минут таки появляется надпись что скачать скрипт не удалось так как адреса по которым плагин ищет обновление мертвы. В консоли так ничего и не появляется.

**Comment by ssbugman** [comment]
Разрешение запуска в приватных окнах на время решило проблему но затем снова перестало работать.

**Comment by HungryDoodles** [comment]
Дополняю.
Ошибки хаотичны.
Иногда gateway.pinata.cloud выдаёт ошибку 504 и страницу Cloudflare: "Gateway time-out".
При попытке зайти через Tor по этому адресу (после проверки безопасности): "The request timed out searching for a file on the non-pinata IPFS network. - ERR_ID:00016".
На повторную попытку установки скрипта тот же самый pinata теперь отвечает 429. Возможно, запросов много.

Upd: перезапустил браузер (кастомный Chrome) и оно работает. Возможно, кратковременный глюк той стороны или браузер что-то прокешировал. 4 раза перевключил без ошибок

**Comment by Serhio666** [comment]
Не работает. При попытки запуска

Информация об ошибках
{
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.63",
  "pup-ext-err": {
    "message": "Не удалось скачать PAC-скрипт с адресов: [ https://e.cen.rodeo:8443/proxy.pac , https://antizapret.prostovpn.org:8443/proxy.pac , https://antizapret.prostovpn.org:18443/proxy.pac , https://antizapret.prostovpn.org/proxy.pac ].",
    "wrapped": {
      "message": "Что-то не так с сетью, проверьте соединение.",
      "wrapped": {
        "stack": "TypeError: Failed to fetch\n    at Object.get (chrome-extension://npgcnondjocldhldegnakemclmfkngch/13-http-lib.js:45:7)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:221:44\n    at new Promise (<anonymous>)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:220:19",
        "message": "Failed to fetch",
        "name": "TypeError"
      }
    }
  }
}

UPD: Запустилось и обновилось

**Comment by ssbugman** [comment]
Снова перестало работать. Ошибок в логах не выдает, просто не работает.

**Comment by ilyaigpetrov** [comment]
Какую ошибку выдаёт браузер при попытке открытия ссылки [1] в новой вкладке? В целях проверки иметь расширение необязательно.

[1]: https://gateway.pinata.cloud/ipfs/QmYwAPJzv5CZsnA625s3Xf2nemtYgPpHdWEz79ojWnPbdG/about
