### ISSUE TITLE
"Ошибка! Не удалось скачать PAC-скрипт с адресов" из-за иностранного IP

### ISSUE THREAD

**Issue by SaskeevKaskee** [anticensority/runet-censorship-bypass#321]
Где-то месяц был в отьезде и вот вернулся и после этого как бы ни пытался, расширение не смог запустить.

Ошибка странная, в начале он не мог скачать PAC-скрипты с адресов (скрин ниже)
![image](https://github.com/user-attachments/assets/c1ce4005-3b9e-401f-a2d6-ff8eca900050)

Далее я полез в файл самопомощи. После переустановки ошибка перестала появляться, но теперь он просто вечно был в режиме (Обновляем..) Отключал все впн, все прокси (сторонние), обновлял браузер к последней версии. К сожалению не помогло.

Также открывал ссылку где можно было раньше отправить репорт на ошибку. Вставлю её ниже:

"userAgent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/129.0.0.0 Safari/537.36",
  "platform": "Win32",
  "version": "0.0.1.63",
  "pup-ext-err": {
    "message": "Не удалось скачать PAC-скрипт с адресов: [ https://e.cen.rodeo:8443/proxy.pac , https://antizapret.prostovpn.org:8443/proxy.pac , https://antizapret.prostovpn.org:18443/proxy.pac , https://antizapret.prostovpn.org/proxy.pac ].",
    "wrapped": {
      "message": "Что-то не так с сетью, проверьте соединение.",
      "wrapped": {
        "stack": "TypeError: Failed to fetch\n    at Object.get (chrome-extension://npgcnondjocldhldegnakemclmfkngch/13-http-lib.js:45:7)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:221:44\n    at new Promise (<anonymous>)\n    at chrome-extension://npgcnondjocldhldegnakemclmfkngch/37-sync-pac-script-with-pac-provider-api.js:220:19",
        "message": "Failed to fetch",
        "name": "TypeError"
      }
    }
  }
}

**Comment by SaskeevKaskee** [comment]
Также в касперском ставил Не проверять защищенные соединения

**Comment by ilyaigpetrov** [comment]
См. https://github.com/anticensority/runet-censorship-bypass/wiki/Частые-проблемы#не-удалось-скачать-pac-скрипт-с-адресов--httpsantizapretprostovpnorgproxypac%2D.

**Comment by SaskeevKaskee** [comment]
Нашел свою ошибку, мой ip определяется как иностранный. Отправил пару дней назад на почту свой ip, но увы пока ни какой реакции, может быть кто-то подскажет, вдруг я сделал что-то не так?

**Comment by ilyaigpetrov** [comment]
> пару дней назад 

Автор проекта АнтиЗапрет несколько загружен -- попробуйте подождать неделю-полторы.

**Comment by SaskeevKaskee** [comment]
> > пару дней назад
> 
> Автор проекта АнтиЗапрет несколько загружен -- сформировал неделю-полторы.


Понял, благодарю за ответ

**Comment by ilyaigpetrov** [comment]
Проблема всё ещё актуальна?
