### ISSUE TITLE
Uncaught Error: Extension context invalidated.

### ISSUE THREAD

**Issue by NTMan** [anticensority/runet-censorship-bypass#50]
В работе расширения произошла ошибка когда я перевел режим работы с "Disable" на "Antizapret"

```
{
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3788.1 Safari/537.36",
  "platform": "Linux x86_64",
  "version": "0.0.1.31",
  "ext-error": {
    "message": "Uncaught Error: Extension context invalidated.",
    "filename": "chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js",
    "lineno": 3761,
    "colno": 30,
    "error": {
      "stack": "Error: Extension context invalidated.\n    at Main.render (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:3761:30)\n    at Main._updateComponent (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:5655:31)\n    at patchComponent (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:7058:42)\n    at patch (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:6824:17)\n    at patchKeyedChildren (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:7248:13)\n    at patchChildren (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:7020:13)\n    at patchElement (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:6892:13)\n    at Object.patch [as internal_patch] (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:6832:17)\n    at applyState (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:5543:21)\n    at queueStateChanges (chrome-extension://npgcnondjocldhldegnakemclmfkngch/pages/options/dist/bundle.min.js:5475:13)",
      "message": "Extension context invalidated.",
      "name": "Error"
    },
    "type": "error"
  }
}
```

**Comment by ilyaigpetrov** [comment]
Спасибо, воспроизвёл в 76 и 74.
Происходит, если окно закрыть до окончания процесса установки или обновления PAC-скрипта.

**Comment by ilyaigpetrov** [comment]
`Extension context invalidated` error is thrown if `window.closed` is true and call to `window.chrome.i18n` or other `window.chrome` api happens. The solution is:
```js
chrome.runtime.getBackgroundPage((bgWindow) => {
  /*
    `Extension context invalidated` error is thrown if `window.closed` is true and call to
    `window.chrome.i18n` or other `window.chrome` api happens. Use bgWindow.chrome instead.
    Use winChrome for tab-related calls like winChrome.tabs.getCurrent.
  */
  window.winChrome = window.chrome;
  window.chrome = bgWindow.chrome;
});
```
